### ISSUE TITLE
Editor config... config

### ISSUE THREAD

**Issue by simmo** [zone/frontend#2]
**Is your feature request related to a problem? Please describe.**
.editorconfig files are support by all major code editors. We need a way to share/install this.

**Describe the solution you'd like**
Running a command to create the file.

**Describe alternatives you've considered**
Extending a config doesn't appear to be possible.

**Additional context**
None

**Comment by martinherweg** [comment]
Is extending needed? If so maybe we could choose an template approach where we create one .editorconfig for everything with conditionals and then copy it on creation with this https://github.com/SBoudrias/mem-fs-editor 

Then we could use Jarvis to install it and choose the answer to just extend it in the way we need it.

**Comment by simmo** [comment]
I like the idea of being able to chunk-up the config and be able to install all or bits of it. This would fit well for jarvis (it uses the inquirer package for UI).
