### ISSUE TITLE
Typo in .editorconfig file

### ISSUE THREAD

**Issue by seaburrows** [zone/frontend#4]
**Describe the bug**
The editor config for this repo will not force an editor to use spaces for indentation, rather the editor default will be used. This is because `.editorconfig` specifies an indent style of `spaces` rather than the singular `space`.

**To Reproduce**
Tricky to replicate in the editor but see the example config here: http://editorconfig.org/
Also the VS Code implementation you can see the values are singular (`space`, `tab`): https://github.com/editorconfig/editorconfig-vscode/blob/master/src/Utils.ts

**Expected behavior**
`indent_style = spaces` to be changed to `indent_style = space`.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by simmo** [comment]
Fixed in commit 93f0b44c198ca4e5eaf201c65928a860751549d4
