### ISSUE TITLE
Switch to NPM

### ISSUE THREAD

**Issue by simmo** [zone/frontend#49]
**Package (if applicable)**
All

**The task**
Switch to NPM:
- [ ] Ensure Travis, Lerna and package.json scripts are updated.
- [ ] Use `npm ci` where applicable.
- [ ] Remove Yarn workspaces
- [ ] Update README
- [ ] Switch yarn.lock > package-lock.json

**Additional context**
NPM CI [appears to be faster that other options available](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable).
When this repo was started Yarn offered a lot more than NPM, now NPM is catching up we should explore.

**Comment by simmo** [comment]
I think this is going to need a deeper look especially around the removal of Yarn workspaces.

**Comment by arashkiani** [comment]
@simmo just wondering why you want to swap yarn with npm ?

**Comment by simmo** [comment]
- @sburrows-zone gave me a nudge that `npm ci` seems to be benchmarking faster - https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
- NPM does security audits by default
