### ISSUE TITLE
Change behaviour of eslint-plugin-compat

### ISSUE THREAD

**Issue by martinherweg** [zone/frontend#5]
**Is your feature request related to a problem? Please describe.**
eslint-plugin-compat adds errors but babel-polyfill is taking care of applying just the polyfills needed for the environment.

**Describe the solution you'd like**
Add eslint-plugin-compat to just warnings and not errors so you still know which polyfills will be applied.

**Additional context**
in the current version of babel-polyfill you can add `"useBuiltIns": "usage"` in the babel config and it figures out which polyfills should get applied depending on the environment.
Source: https://medium.freecodecamp.org/were-nearing-the-7-0-babel-release-here-s-all-the-cool-stuff-we-ve-been-doing-8c1ade684039

**Comment by simmo** [comment]
eslint-config-zone > rules`compat/compat` needs setting to 'warn' and we'll need to add a bit of info to the readme file.

**Comment by simmo** [comment]
#6

**Comment by simmo** [comment]
PR merged, pending publish.
